<?php

return [
    //
    'quotes' => [
    	"Don’t worry if it doesn’t work right. If everything did, you’d be out of a job. - Mosher’s Law of Software Engineering",
        "I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing. - Oktal",
        "I don't care if it works on your machine! We are not shipping your machine! - Vidiu Platon",
        "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code - Benjamin Valbret",
        "Measuring programming progress by lines of code is like measuring aircraft building progress by weight - Bill Gates",
        "First learn computer science and all the theory. Next develop a programming style. Then forget all that and just hack - George Carrette",
        "To iterate is human, to recurse divine. - L. Peter Deutsch",
        "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program. - Linus Torvalds",
        "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Martin Golding",
        "There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies. And the other way is to make it so complicated that there are no obvious deficiencies. -  C.A.R. Hoare",
        "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. - Seymour Cray",
        "Java is to JavaScript what Car is to Carpet. - Chris Heilmann",
        "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
        "Walking on water and developing software from a specification are easy if both are frozen - Edward V Berard",
        "First, solve the problem. Then, write the code. - John Johnson",
        "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
        "Linux is only free if your time has no value. - Jamie Zawinski",
        "Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald Knuth",
        "Good code is its own best documentation. As you're about to add a comment, ask yourself, 'How can I improve the code so that this comment isn't needed?' Improve the code and then document it to make it even clearer. -  Steve McConnell",
        "Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves. - Kreitzberg and Shneiderman",
        "Programming can be fun, so can cryptography; however they should not be combined. - Kreitzberg and Shneiderman",
        "Copy and paste is a design error. - David Parnas",
        "Before software can be reusable it first has to be usable. - Ralph Johnson",
        "Computers are good at following instructions, but not at reading your mind. - Donald Knuth",
        "Any code of your own that you haven't looked at for six or more months might as well have been written by someone else. -  Eagleson's law",
        "Talk is cheap. Show me the code. - Linus Torvalds",
        "Programming is like sex. One mistake and you have to support it for the rest of your life - Michael Sinz",
        "A good programmer is someone who always looks both ways before crossing a one-way street - Doug Linder",
        "From a programmer's point of view, the user is a peripheral that types when you issue a read request. - Peter Williams",
        "Version 1 of any software is full of bugs. Version 2 fixes all the bugs and is great. Version 3 adds all the things users ask for, but hides all the great stuff in Version 2 - Fred Blechman",
        "One man's crappy software is another man's full time job. - Jessica Gaston",
        "It's okay to figure out murder mysteries, but you shouldn't need to figure out code. You should be able to read it. - Steve McConnell",
        "One man's constant is another man's variable - Alan J. Perlis",
        "There does not now, nor will there ever exist, a programming language in which it is the least bit hard to write bad programs. - Lawrence Flon",
        "When debugging, novices insert corrective code; experts remove defective code. - Richard Pattis",
        "In programming, as in everything else, to be in error is to be reborn. - Alan J. Perlis",
        "One of my most productive days was throwing away 1000 lines of code. - Ken Thompson",
        "Deleted code is debugged code. - Jeff Sickel",
        "Controlling complexity is the essence of computer programming. - Brian Kernighan",
        "Just heard a QA \"Engineeer\" ask a customer on the phone - \"What made you wanna do THAT!??\" - Kevin Marois",
        "The main purpose of multidimensional arrays in C++ is to confuse beginners and generate an endless stream of questions about how to allocate them dynamically, about how to delete them, or why they can't be converted to pointers to pointers. –  R. Martinho Fernandes",
        "When you don't create things, you become defined by your tastes rather than ability. your tastes only narrow & exclude people. so create. – Why The Lucky Stiff",
        "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelsons",
        "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning. – Rick Cook",
        "That's the thing about people who think they hate computers. What they really hate is lousy programmers. – Larry Niven",
        "Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime. ― Muhammad Waseem",
        "I'm not a great programmer; I'm just a good programmer with great habits. ― Kent Beck",
        "Truth can only be found in one place: the code. ― Robert C. Martin",
        "How you look at it is pretty much how you'll see it. ― Rasheed Ogunlaru",
        "You've baked a really lovely cake, but then you've used dog shit for frosting. ― Steve Jobs",
        "Everyone knows that debugging is twice as hard as writing a program in the first place. So if you're as clever as you can be when you write it, how will you ever debug it? ― Brian Kernighan",
        "A language that doesn't affect the way you think about programming is not worth knowing. ― Alan J. Perlis",
        "If you're good at something, never do it for free. ― Heath Ledger",
        "The most disastrous thing that you can ever learn is your first programming language. ― Alan Kay",
        "Perl – The only language that looks the same before and after RSA encryption. ― Keith Bostic",
        "The most important property of a program is whether it accomplishes the intention of its user. ― C.A.R. Hoare",
        "Object-oriented programming offers a sustainable way to write spaghetti code. It lets you accrete programs as a series of patches. ― Paul Graham",
        "At forty, I was too old to work as a programmer myself anymore; writing code is a young person’s job. ― Michael Crichton, Prey",
    ]
];